### ISSUE TITLE
Why doesn't this work?

### ISSUE THREAD

**Issue by rrivera1849** [cgtboy1988/Frontir#1]
Why do you write horrible code man? Like, wtf is this language. Who uses Java, it's so antiquated bra.

BRAAAAAA

Troll

Just trolling, thanks bra.

**Comment by taylor239** [comment]
I figured a true cybergod would be able to fix the mistakes in the code like I have on my own deployment.  Not meant for plebs.  Oops.

**Comment by taylor239** [comment]
Fixd /w reme

**Comment by rrivera1849** [comment]
Very nice fix, quick and 1337
